name: pesepay
description: Pesepay helps businesses in Africa get paid by anyone, anywhere in the world
version: 0.4.0
homepage: https://github.com/iamngoni/pesepay

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.0.1
  encrypt: ^5.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  localregex: ^4.0.5

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
