name: pesepay
description: Pesepay helps businesses in Africa get paid by anyone, anywhere in the world
version: 0.1.0+1
homepage: https://github.com/iamngoni/pesepay


environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dio: ^5.0.1
  encrypt: ^5.0.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.8.0
  localregex: ^4.0.2
  logger:

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.1.0+1
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
